BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[TmstDetectionLogs] (
    [id] INT NOT NULL IDENTITY(1,1),
    [status] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [TmstDetectionLogs_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [TmstDetectionLogs_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
